version: "3"

services:
  app:
    build: ./app
    volumes:
      - ./app:/app

  mongo:
    image: mongo
    command: --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - ./app/database:/app/database

